### ISSUE TITLE
Suggestion: Add docstring formatter

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-t2d#164]
The last few reviews (e.g., #148) had errors mainly related to docstrings.

Therefore I suggest adding [pycodestyle](https://github.com/PyCQA/pycodestyle) and [darglint](https://github.com/terrencepreilly/darglint) to our pre-commit hooks.

pycodestyle check for style conventions in the docstring (initial tests seem promising, although potentially too strict). darglint checks whether the description matches the implementation (e.g., type hints consistency).

This should reduce 1) time spent on code review, 2) reduce cycles in code review (see #148) 3) Remove inconsistencies between code and documentation.

Couldn't I find an autoformatter, sadly (darglint has it on its roadmap).

Suggestion for darglint settings:
in file `.darglint`:
```
[darglint]
ignore=DAR401
strictness=short
```

Potential frustrations with darglint:
Does not support ", optional" type hints:
```python
# valid
test_size (float): test_size is the test size...
# not valid
test_size (float, optional): test_size is the test size...
# but is valid (if type hint match)
test_size (Optional[float]): test_size is the test size...

```
you can choose to ignore: DAR103

Adding to pre-commit (flake8-docstrings == pycodestyle):
```

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        files: ^src/
        args:
        - --ignore=D203,D204,D213,D215,D400,D401,D404,D406,D407,D408,D409,D413,D104
      # ignore corresponds to google docstring conventions
      # with the additions of: 
      # D104: require docstring in __init__.py

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
```
