### ISSUE TITLE
Hydra and XGBoost conf options

### ISSUE THREAD

**Issue by martbern** [Aarhus-Psychiatry-Research/psycop-t2d#86]
Might be helpful for your PR @KennethEnevoldsen:

```yaml
xgboost:
  verbosity: 0
  nthread: 60 (Want this to be general for "train")
  lambda: tag(log, interval(1e-8, 1.0))
  alpha: tag(log, interval(1e-8, 1.0))
```

**Then either this set:**
```yaml
  booster: choice(["gbtree", "gblinear"])
  max_depth: int(interval(1, 9))
  learning_rate: tag(log, interval(1e-8, 1.0))
  gamma: tag(log, interval(1e-8, 1.0))
  grow_policy: choice(["depthwise", "lossguide"])
```

**Or this set:**
```yaml
  booster: "dart"
  sample_type: choice(["uniform", "weighted"])
  normalize_type: choice(["tree", "forest"])
  rate_drop: tag(log, interval(1e-8, 1.0))
  skip_drop: tag(log, interval(1e-8, 1.0))
```

From here: https://medium.com/optuna/using-optuna-to-optimize-xgboost-hyperparameters-63bfcdfd3407

```yaml
defaults:
  override hydra/sweeper: optuna
    
hydra:
  sweeper:
    optuna_config:
      sampler: tpe
      n_trials: 100
      n_jobs: 60
      seed: 123
```
